// llm_lua_bindings.snippet.cpp
//
// This is NOT a standalone compilable file -- it's a snippet to splice into
// your existing esp32/lua_engine.cpp, following the exact same pattern
// already used there for esp32.robot.*, esp32.fs.*, etc. See
// firmware/INTEGRATION.md for exactly where each piece goes.

// 1) Near the top of lua_engine.cpp, alongside the other #includes:
//
//      #include "llm_engine.h"
//      #include "llm_tokenizer.h"
//      #include "vocab_data.h"     // generated by tools/quantize_and_convert.py
//      // #include "model_data.h"  // only if baking the model in as a C array
//
// 2) Somewhere in namespace LLMEngine (or right here), one global engine
//    instance -- mirrors how lua_engine.cpp keeps a single global lua_State* L:

static LLMEngine::Engine g_llm;

// 3) The two bound functions, in the same style as l_robot_forward etc.:

static int l_llm_load(lua_State* Ls) {
  const char* path = luaL_optstring(Ls, 1, "");
  LLMTokenizer::Vocab vocab{ esp32_llm_vocab, esp32_llm_vocab_size };

  bool ok;
  if (strlen(path) == 0) {
    // Baked-in C array path -- requires model_data.h to have been included
    // above and uncommented.
    // ok = g_llm.load(esp32_llm_model, esp32_llm_model_len, vocab);
    ok = false; // left disabled until model_data.h is actually wired in
  } else {
    ok = g_llm.loadFromFile(FsManager::activeFs(), path, vocab);
  }
  lua_pushboolean(Ls, ok);
  return 1;
}

static int l_llm_generate(lua_State* Ls) {
  const char* prompt = luaL_checkstring(Ls, 1);
  int maxNew = (int)luaL_optinteger(Ls, 2, 64);
  String out = g_llm.generate(String(prompt), maxNew);
  lua_pushstring(Ls, out.c_str());
  return 1;
}

static const luaL_Reg llmFuncs[] = {
  {"load", l_llm_load},
  {"generate", l_llm_generate},
  {NULL, NULL}
};

// 4) Inside LLMEngine::begin() (called "begin()" in the existing
//    lua_engine.cpp -- the function that builds the esp32.* table), add
//    one line alongside the other pushSubtable(...) calls:
//
//      pushSubtable(L, llmFuncs); lua_setfield(L, -2, "llm");
//
// That's it -- esp32.llm.load(path) and esp32.llm.generate(prompt, n)
// are now callable from any Lua script, including main.lua in this zip.
