#!/usr/bin/env python3
"""
quantize_and_convert.py -- converts trained transformer weights into the
int8 model.bin format expected by firmware/llm_engine.h, plus a vocab_data.h
header. See tools/README.md for the exact binary layout and for what
EXPECTED_ARRAYS below assumes your training script produced.

Usage:
  python quantize_and_convert.py --weights weights.npz --vocab vocab.txt \
      --out-bin model.bin --out-vocab vocab_data.h

Expects a .npz (numpy savez) with these arrays (shapes shown for one layer;
per-layer arrays are stacked along a leading n_layers axis):

  tok_embeddings          [vocab_size, dim]
  rms_att_weight          [n_layers, dim]
  wq, wk, wv              [n_layers, dim, n_heads*head_size] (wk/wv use n_kv_heads)
  wo                      [n_layers, n_heads*head_size, dim]
  rms_ffn_weight          [n_layers, dim]
  w1, w3                  [n_layers, dim, hidden_dim]
  w2                      [n_layers, hidden_dim, dim]
  rms_final_weight        [dim]
  wcls                    [dim, vocab_size]

Adapt EXPECTED_ARRAYS / the reshape logic below if your own training script
names or shapes things differently -- this is meant to be edited, not used
as an untouched black box.
"""
import argparse
import struct
import sys

import numpy as np

EXPECTED_ARRAYS = [
    "tok_embeddings", "rms_att_weight", "wq", "wk", "wv", "wo",
    "rms_ffn_weight", "w1", "w2", "w3", "rms_final_weight", "wcls",
]


def quantize(mat: np.ndarray):
    """Single symmetric scale per tensor: scale = max(abs(w))/127."""
    maxval = float(np.max(np.abs(mat))) or 1e-8
    scale = maxval / 127.0
    q = np.round(mat / scale).clip(-127, 127).astype(np.int8)
    return q, scale


def write_qmatrix(f, mat: np.ndarray):
    q, scale = quantize(mat)
    f.write(q.tobytes(order="C"))
    f.write(struct.pack("<f", scale))


def write_fvector(f, vec: np.ndarray):
    f.write(vec.astype(np.float32).tobytes(order="C"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--weights", required=True, help="input .npz with EXPECTED_ARRAYS")
    ap.add_argument("--vocab", required=True, help="vocab file, one token per line, in id order")
    ap.add_argument("--out-bin", required=True)
    ap.add_argument("--out-vocab", required=True)
    ap.add_argument("--n-heads", type=int, required=True)
    ap.add_argument("--n-kv-heads", type=int, required=True)
    ap.add_argument("--seq-len", type=int, required=True)
    args = ap.parse_args()

    data = np.load(args.weights)
    for name in EXPECTED_ARRAYS:
        if name not in data:
            sys.exit(f"error: missing array '{name}' in {args.weights}")

    vocab_size, dim = data["tok_embeddings"].shape
    n_layers = data["rms_att_weight"].shape[0]
    hidden_dim = data["w1"].shape[2]

    with open(args.out_bin, "wb") as f:
        f.write(struct.pack(
            "<7i", dim, hidden_dim, n_layers, args.n_heads,
            args.n_kv_heads, vocab_size, args.seq_len,
        ))

        write_qmatrix(f, data["tok_embeddings"])

        for l in range(n_layers):
            write_fvector(f, data["rms_att_weight"][l])
            write_qmatrix(f, data["wq"][l])
            write_qmatrix(f, data["wk"][l])
            write_qmatrix(f, data["wv"][l])
            write_qmatrix(f, data["wo"][l])
            write_fvector(f, data["rms_ffn_weight"][l])
            write_qmatrix(f, data["w1"][l])
            write_qmatrix(f, data["w2"][l])
            write_qmatrix(f, data["w3"][l])

        write_fvector(f, data["rms_final_weight"])
        write_qmatrix(f, data["wcls"])

    print(f"wrote {args.out_bin} "
          f"(dim={dim} hidden_dim={hidden_dim} n_layers={n_layers} "
          f"vocab_size={vocab_size})")

    with open(args.vocab, encoding="utf-8") as vf:
        tokens = [line.rstrip("\n") for line in vf]

    with open(args.out_vocab, "w", encoding="utf-8") as hf:
        hf.write("// Auto-generated by tools/quantize_and_convert.py -- do not hand-edit.\n")
        hf.write("#pragma once\n\n")
        hf.write(f"static const int32_t esp32_llm_vocab_size = {len(tokens)};\n")
        hf.write("static const char* const esp32_llm_vocab[] = {\n")
        for t in tokens:
            escaped = t.replace("\\", "\\\\").replace('"', '\\"')
            hf.write(f'  "{escaped}",\n')
        hf.write("};\n")

    print(f"wrote {args.out_vocab} ({len(tokens)} tokens)")


if __name__ == "__main__":
    main()
